---
- name: 'atualizando repos'
  apt:
    update_cache: yes
  become: yes

- name: Incluindo repositorio JDK 8
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Aceptando a licença do JDK 8
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Instalando JDK 8 e dependencias
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
    - git
    - maven
    - systemd
    - htop