---
- name: 'atualizando repos'
  apt:
    update_cache: yes
  become: yes

- name: Incluindo repositorio JDK 8
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Aceptando a licença do JDK 8
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Instalando JDK 8 e dependencias
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
    - git
    - maven
    - systemd
    - htop

- name: 'Criando diretorio pro PhantomJS'
  file:
    path: '/opt/PhantomJS/'
    state: directory
  become: yes
  
- name: 'Copia o PhantomJS'
  copy:
    src: 'files/phantomjs-2.1.1-linux-x86_64.tar.bz2'
    dest: '/tmp/phantomjs-2.1.1-linux-x86_64.tar.bz2'
  become: yes

- name: 'Descompactando PhantomJS'
  unarchive:
    src: '/tmp/phantomjs-2.1.1-linux-x86_64.tar.bz2'
    dest: '/opt/PhantomJS/'
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes