---
- name: 'Criando grupo Tomcat'
  group:
    name: tomcat
    state: present
  become: yes

- name: 'Criando usuario Tomcat'
  user:
    name: tomcat
    shell: /bin/false
    groups: tomcat
    home: /opt/tomcat
  become: yes

#- name: 'Baixa o Tomcat8'
#  get_url:
#    url: 'http://ftp.unicamp.br/pub/apache/tomcat/tomcat-8/v8.5.34/bin/apache-tomcat-8.5.34.tar.gz'
#    dest: '/tmp/apache-tomcat-8.5.34.tar.gz'

- name: 'Copia o Tomcat8'
  copy:
    src: 'files/apache-tomcat-8.5.34.tar.gz'
    dest: '/tmp/apache-tomcat-8.5.34.tar.gz'
  become: yes

- name: 'Descompactando Tomcat'
  unarchive:
    src: '/tmp/apache-tomcat-8.5.34.tar.gz'
    dest: /opt/tomcat/
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes

- name: 'Setando grupo tomcat da pasta /opt/tomcat/'
  file:
    path: '/opt/tomcat'
    group: tomcat
    recurse: yes
  become: yes

- name: 'Setando leitura da pasta /opt/tomcat/conf'
  file:
    path: '/opt/tomcat/conf'
    mode: 'g+r'
    recurse: yes
  become: yes

- name: 'Setando execução da pasta /opt/tomcat/conf'
  file:
    path: '/opt/tomcat/conf'
    mode: 'g+x'
  become: yes
  
- name: 'Setando owner tomcat das pastas necessarias do diretorio /opt/tomcat'
  file:
    path: '/opt/tomcat/{{ item }}'
    owner: tomcat
    recurse: yes
  with_items:
    - webapps/
    - work/
    - temp/
    - logs
  become: yes

- name: 'Configura o serviço do Tomcat'
  template:
    src: 'templates/tomcat.service.j2'
    dest: '/etc/systemd/system/tomcat.service'
  become: yes

- name: 'Recarregando Serviços'
  systemd:
    daemon_reload: yes
  become: yes
    
- name: 'iniciando serviço Tomcat8'
  systemd:
    state: started
    name: tomcat
  become: yes